### ISSUE TITLE
Nonce too low error

### ISSUE THREAD

**Issue by facundomedica** [umee-network/peggo#80]
## Summary of Bug

This is an error we've been seeing sporadically for a while, it looks like it's not dangerous at all, a simple restart fixes it, but I would like to know why it happens in the first place.

```
5:00PM ERR sendTransaction failed error="nonce too low" module=ethCommiter tx_hash=0x9a29ff7ea9c26def63ced06a3cc59f906b8d4157ef85f4be336379f9bbe9ea25 tx_hash_ret=0x0000000000000000000000000000000000000000000000000000000000000000
```

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
So two things:

1. Injective solved this via the eth mempool feature, which I believe we now have support for.
2. Having to restart is not ideal. Operators are not going to be watching peggo -- they're going to have it run via systemd or some other service monitor process. I feel like we should gracefully exit if peggo cannot recover on its own.

**Comment by chalermporn17** [comment]
It's very dangerous for me though.
after this error happen it's will try to send tx until it's successful ( also don't know why it resend ) and when everything work it's will send all tx ( which is before failed because "Nonce too low" )  in one go and cause heavily lost.

may be cause has been mention [here](https://github.com/umee-network/peggo/issues/122)
